# Introducción a Numpy

Numpy (Numerical Python) es una librería para manejar arreglos de datos. 

* Documentación: https://numpy.org/
* Una guía de uso: https://platzi.com/blog/numpy/

Ahora haremos algunos ejercicios.

In [ ]:
import numpy as np

In [ ]:
np.array([10, 20, 24, 5, 15, 50])

array([10, 20, 24,  5, 15, 50])

In [ ]:
a = np.array([10, 30, 20, 4, 30, 51, 7, 2, 4, 40, 100])
a[4]

30

Para acceder a una fracción de todo el arreglo:

In [ ]:
a[3:]

array([  4,  30,  51,   7,   2,   4,  40, 100])

In [ ]:
a[3:7]

array([ 4, 30, 51,  7])

Para acceder a una porción, pero especificando el espaciado usamos doble dos puntos `::`.

In [ ]:
a[1::4]

array([30, 51, 40])

Puedes crear matrices de ceros o unos. Los métodos te devuelven flotantes.

In [ ]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
type(np.ones(10)[6])

numpy.float64

Ordenando valores.

In [ ]:
c = np.array([4, 5, 1, 34, 12, 76, 1, 2])
np.sort(c)

array([ 1,  1,  2,  4,  5, 12, 34, 76])

In [ ]:
cabeceras = [ ('nombre', 'S10' ), ('edad', int) ]
datos = [ ('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15) ]
usuarios = np.array(datos, dtype = cabeceras)

np.sort(usuarios, order = 'edad' )

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i8')])

### Arange and linspace

In [ ]:
np.linspace(2, 17, 4)

array([ 2.,  7., 12., 17.])

In [ ]:
np.arange(13)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.arange(5,13)

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
np.arange(2, 17, 4)

array([ 2,  6, 10, 14])

In [ ]:
np.full((3, 5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [ ]:
np.diag ( [0, 3, 9, 10] )

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=041dfe44-1bec-412b-9d74-e111f757f0ed' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>